# Generated by Django 4.0.4 on 2022-05-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_model',
            name='Content',
            field=models.TextField(max_length=70000),
        ),
    ]
