# Generated by Django 4.0.4 on 2022-05-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnoApp', '0002_alter_new_model_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback1', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='new_model',
            name='Word',
            field=models.CharField(max_length=255),
        ),
    ]
